blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/harshankur/officeParser/discussions
    about: For general questions and support, please use our Discussions page.
